# Generated by Django 5.0.3 on 2024-04-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Comedor', 'Comedor'), ('Llevar', 'Llevar')], default='Comedor', max_length=20, null=True, verbose_name='Tipo')),
                ('estado', models.CharField(blank=True, choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='en_proceso', max_length=20, null=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre')),
                ('cantidad', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad')),
                ('precio_unitario', models.PositiveBigIntegerField(default=0, verbose_name='Precio Unitario')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('ffecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='AppCarrito.pedido')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
