# Generated by Django 5.0.6 on 2024-06-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0001_initial'),
        ('Inventario2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVentaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario2.productosinventario')),
                ('producto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCarrito.productoventa')),
            ],
        ),
        migrations.AddField(
            model_name='productoventa',
            name='productos_inventario',
            field=models.ManyToManyField(through='AppCarrito.ProductoVentaInventario', to='Inventario2.productosinventario'),
        ),
    ]
