# Generated by Django 5.0.3 on 2024-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='ffecha',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio_total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Precio Total'),
        ),
    ]
