# Generated by Django 5.0.6 on 2024-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0002_remove_productos_ffecha_productos_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='id_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
