# Generated by Django 5.0.6 on 2024-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(blank=True, null=True, verbose_name='ID Producto')),
                ('id_proveedor', models.IntegerField(blank=True, null=True, verbose_name='ID Proveedor')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre')),
                ('cantidad_en_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en Stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_ingreso', models.CharField(default=' ', max_length=90, verbose_name='Fecha de Ingreso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Producto en Inventario',
                'verbose_name_plural': 'Productos en Inventario',
            },
        ),
    ]
